### ISSUE TITLE
It often breaks down after being update

### ISSUE THREAD

**Issue by phenix13** [werthdavid/homebridge-weather#3]
！！！

**Comment by lnxbil** [comment]
Yepp, it does :-(

```
[2017-6-18 14:43:06] [Wetter Temperatur] Returning cached data Humidity 53
/home/homekit/node-v8.1.2-linux-x64/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Service.js:148
  this.getCharacteristic(name).setValue(value);
                              ^

TypeError: Cannot read property 'setValue' of undefined
    at Service.TemperatureSensor.Service.setCharacteristic (/home/homekit/node-v8.1.2-linux-x64/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Service.js:148:31)
    at WeatherAccessory.getStateHum (/home/homekit/node-v8.1.2-linux-x64/lib/node_modules/homebridge-weather/index.js:96:36)
    at emitThree (events.js:135:13)
    at Characteristic.CurrentRelativeHumidity.emit (events.js:216:7)
    at Characteristic.CurrentRelativeHumidity.Characteristic.getValue (/home/homekit/node-v8.1.2-linux-x64/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:129:10)
    at Bridge.<anonymous> (/home/homekit/node-v8.1.2-linux-x64/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:650:20)
    at Array.forEach (native)
    at Bridge.Accessory._handleGetCharacteristics (/home/homekit/node-v8.1.2-linux-x64/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:614:8)
    at emitMany (events.js:146:13)
    at HAPServer.emit (events.js:223:7)
    at HAPServer._handleCharacteristics (/home/homekit/node-v8.1.2-linux-x64/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:926:10)
    at HAPServer.<anonymous> (/home/homekit/node-v8.1.2-linux-x64/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at emitNone (events.js:105:13)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
```

**Comment by fabergoncalves** [comment]
Yeah, having the same problem here

**Comment by Scream4Life** [comment]
Is this someting planned to be fixed? It happens all the time after a few seconds for me. Actually unusable.

**Comment by friko21** [comment]
This line in getStateHum is the problem:
                temperatureService.setCharacteristic(Characteristic.CurrentRelativeHumidity, this.humidity);

There he tries to bind CurrentRelativeHumidity to his temperatureService, with doesn't know anything about humidity.

**Comment by werthdavid** [comment]
Will look into it!

**Comment by werthdavid** [comment]
Should be fixed
